// Localized labels for Aerial videos, categories, and subcategories.
// Backed by src/data/videos-i18n.json which is generated by
// scripts/build-videos.mjs from Apple's loctable bundle.
//
// All lookups fall back to the English label, then to the raw key, so a
// missing translation never blanks out the UI.
import data from '../data/videos-i18n.json';

const FALLBACK = 'en';

export function videoName(shotID, locale) {
  if (!shotID) return null;
  const entry = data.videos[shotID];
  if (!entry) return null;
  return entry[locale] ?? entry[FALLBACK] ?? null;
}

export function categoryName(category, locale) {
  if (!category) return null;
  const entry = data.categories[category];
  if (!entry) return category;
  return entry[locale] ?? entry[FALLBACK] ?? category;
}

export function subcategoryName(sub, locale) {
  if (!sub) return null;
  const entry = data.subcategories[sub];
  if (!entry) return sub;
  return entry[locale] ?? entry[FALLBACK] ?? sub;
}
