# Load necessary modules
LoadModule headers_module libexec/apache2/mod_headers.so

# Run Apache as current user to access user directories
User YOUR_MAC_USER_NAME
Group staff

# Listen to port 18000
Listen 18000

<VirtualHost *:18000>
    # CORS Headers
    Header always set Access-Control-Allow-Origin "*"
    
    # Alias /videos to the actual videos directory
    Alias /videos "/Users/YOUR_MAC_USER_NAME/Library/Application Support/com.apple.wallpaper/aerials/videos"
    
    # Directory configuration for the videos directory
    <Directory "/Users/YOUR_MAC_USER_NAME/Library/Application Support/com.apple.wallpaper/aerials/videos">
        Options +Indexes
        Require all granted
    </Directory>
    
    # Error logs
    ErrorLog "/var/log/apache2/error_log"
    CustomLog "/var/log/apache2/access_log" common
</VirtualHost>
